services:
  rtmp:
    build: 
      context: ./nginx_test
    ports:
      - "1935:1935"
      - "8000:8000"
      - "3001:3001"

  backend:
    build: ./back
    ports:
      - "8001:8001"
    environment:
      - HUGGINGFACEHUB_API_TOKEN=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

