version: '3.12'

services:
  frontend:
    build: 
      context: ./front  # React 프로젝트 디렉토리
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./back  # 현재 디렉토리 (Python 백엔드)
    ports:
      - "8000:8000"
    env_file:
      - /back/.env  # 기존에 설정해둔 DB 연결 정보가 있는 환경변수 파일